name: nabbda
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^19.3.45+1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  responsive_framework: ^0.1.4
  charts_flutter: ^0.11.0
  auto_size_text: ^3.0.0-nullsafety.0
  chart_sparkline: ^1.0.5
  percent_indicator: ^3.4.0
  expansion_tile_card: ^2.0.0
  google_maps_flutter: ^2.0.11
  agora_rtc_engine: ^4.0.1
  get: ^4.3.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_timer: ^0.0.6
  table_calendar: ^3.0.0
    


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:     

    - assets/images/heart.svg
    - assets/images/Track.jpg
    - assets/images/Reminders.png
    - assets/images/goo.svg
    - assets/images/regist.svg
    - assets/images/lock.svg
    - assets/images/code.svg
    - assets/images/open.png
    - assets/images/success.svg
    - assets/images/home.png
    - assets/images/medical.svg
    - assets/images/high.svg
    - assets/images/vital.svg
    - assets/images/low.svg
    - assets/images/health.svg
    - assets/images/medical2.svg
    - assets/images/mental.svg
    - assets/images/avatar.png
    - assets/images/changeProfilePicture.jpg
    - assets/images/Report.jpg
    - assets/images/data.png
    - assets/images/calc1.svg
    - assets/images/calc2.svg
    - assets/images/calc3.svg
    - assets/images/Female.png
    - assets/images/Male.png
    - assets/images/med4.svg
    - assets/images/med3.svg
    - assets/images/med2.svg
    - assets/images/med1.svg
    - assets/images/docum.svg
    - assets/images/medical.png
    - assets/images/nabbda.svg
    - assets/images/Group.svg
    - assets/images/Error.svg
    - assets/images/qxmd.svg
    - assets/images/ASCVD.svg
    - assets/images/Stroke.svg
    - assets/images/arteries.svg
    - assets/images/heart1.svg
    - assets/images/Female.svg
    - assets/images/Male.svg
    - assets/images/Female.svg
    - assets/images/Data.svg
    - assets/images/DrMohamed.svg
    - assets/images/Bank1.png
    - assets/images/Bank2.png
    - assets/images/Bank3.png
    - assets/images/Sent.png
    



    - assets/images/

    



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: nabbdaIcons
      fonts:
        - asset: assets/fonts/nabbdaIcons.ttf

        
    - family: NavigationBarIcons
      fonts:
        - asset: assets/fonts/NavigationIcons.ttf





  




  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
