/// Flutter icons Picker
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Picker
///      fonts:
///       - asset: fonts/Picker.ttf
///
///
///
import 'package:flutter/widgets.dart';

class NavigationIcons {
  NavigationIcons._();

  static const _kFontFam = 'navigationIcons';
  static const String? _kFontPkg = null;

  static const IconData home =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pills =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bmi =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
